version: "3.9"
services:
  app:
    image: gotodo
    container_name: app
    build:
      args:
        - target=dev
    environment:
      TODO_ENV: dev
      PORT: 8080
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: todo
      DB_PASSWORD: todo
      DB_DATABASE: todo
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - .:/app
    ports:
      - "18000:8080"
    depends_on:
      - "db"
      - "redis"
  db:
    image: mysql:8.0.29
    platform: linux/amd64
    container_name: db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo
      MYSQL_DATABASE: todo
    volumes:
      - db-data:/var/lib/mysql
      - $PWD/_tools/mysql/conf.d:/etc/mysql/conf.d:cached
    ports:
      - "33306:3306"
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "36379:6379"


volumes:
  db-data:
